export const CODE_LORE_CITY_PERFORMANCE = Object.freeze([
    "CODELORE|city-performance.js|0001|@quantitative-parameterized -- generated; edit build-parameter-catalog.cjs to rebuild",
    "CODELORE|city-performance.js|0002|Performance infrastructure for the procedural city.",
    "CODELORE|city-performance.js|0003|The city is almost entirely static after generation. Scaling it by raw",
    "CODELORE|city-performance.js|0004|object count therefore wastes CPU in three places that have nothing to do",
    "CODELORE|city-performance.js|0005|with what is actually visible: generation-time all-to-all scans, per-frame",
    "CODELORE|city-performance.js|0006|world-matrix walks, and renderer traversal of far-away geometry. This module",
    "CODELORE|city-performance.js|0007|provides two intentionally boring primitives that attack those costs without",
    "CODELORE|city-performance.js|0008|changing gameplay geometry:",
    "CODELORE|city-performance.js|0009|1) SpatialHash2D for local generation/broadphase queries.",
    "CODELORE|city-performance.js|0010|2) createStaticWorldOptimizer() for render chunks, material dedupe,",
    "CODELORE|city-performance.js|0011|conservative static mesh batching, and static matrix freezing.",
    "CODELORE|city-performance.js|0012|ix -> Map(iz -> Array(items))",
    "CODELORE|city-performance.js|0013|Custom shader hooks can make two superficially identical materials",
    "CODELORE|city-performance.js|0014|render differently. Leave those alone rather than over-deduplicating.",
    "CODELORE|city-performance.js|0015|Batches are attached directly to an identity-transform render chunk.",
    "CODELORE|city-performance.js|0016|Bake the full world transform so eligible meshes can be merged even",
    "CODELORE|city-performance.js|0017|when they originated inside nested furniture/building Groups. Keep the",
    "CODELORE|city-performance.js|0018|source index: expanding boxes/planes to non-indexed triangles needlessly",
    "CODELORE|city-performance.js|0019|multiplies vertex memory on the very large cities this path is for.",
    "CODELORE|city-performance.js|0020|Update once so every descendant has a final world matrix. Collecting",
    "CODELORE|city-performance.js|0021|recursively lets a chunk merge repeated rails/steps/walls even when",
    "CODELORE|city-performance.js|0022|their authoring helpers wrapped them in nested Groups.",
    "CODELORE|city-performance.js|0023|Progressive twin of createStaticWorldOptimizer. The rendered result uses the",
    "CODELORE|city-performance.js|0024|same chunking, material dedupe, conservative mesh merging, empty-group",
    "CODELORE|city-performance.js|0025|pruning and matrix freezing as the synchronous optimizer below. The only",
    "CODELORE|city-performance.js|0026|difference is scheduling: each root/chunk is a yield boundary, and the",
    "CODELORE|city-performance.js|0027|controller exists before optimization starts so async GLTF/photo arrivals can",
    "CODELORE|city-performance.js|0028|be queued safely while the optimizer is between slices.",
    "CODELORE|city-performance.js|0029|Incremental chunks may have been frozen after an earlier commit and",
    "CODELORE|city-performance.js|0030|then received another late/static root. Temporarily permit the group",
    "CODELORE|city-performance.js|0031|to propagate world matrices, rebatch everything currently in it, then",
    "CODELORE|city-performance.js|0032|freeze the final chunk again.",
    "CODELORE|city-performance.js|0033|Large/static globals (the city-sized base plane, fixed lights, etc.)",
    "CODELORE|city-performance.js|0034|intentionally never belonged to a spatial chunk. Freeze them one root",
    "CODELORE|city-performance.js|0035|at a time without disabling scene-wide matrix updates: async assets and",
    "CODELORE|city-performance.js|0036|deferred decoration are still allowed to arrive after this point.",
    "CODELORE|city-performance.js|0037|Direct scene roots are cheap to order without recursively measuring",
    "CODELORE|city-performance.js|0038|every object up front. Exact bounds are still computed by placeObject",
    "CODELORE|city-performance.js|0039|before a root is assigned to a render chunk.",
    "CODELORE|city-performance.js|0040|Descending sort + pop keeps the nearest currently-known root at",
    "CODELORE|city-performance.js|0041|the end without O(n) shift operations.",
    "CODELORE|city-performance.js|0042|Optimize visible/near chunks first. Re-sort after every yielded chunk",
    "CODELORE|city-performance.js|0043|so walking during boot changes what gets merged next, not what exists.",
    "CODELORE|city-performance.js|0044|Anything too large/dynamic to live in a render chunk remains a scene",
    "CODELORE|city-performance.js|0045|root. Static globals still get material dedupe + one-time matrix",
    "CODELORE|city-performance.js|0046|freezing, one root per cooperative slice.",
    "CODELORE|city-performance.js|0047|All static descendants now own final matrixWorld values. Disabling the",
    "CODELORE|city-performance.js|0048|scene-wide walk is the same final state as the synchronous optimizer,",
    "CODELORE|city-performance.js|0049|without one last full-tree update spike.",
    "CODELORE|city-performance.js|0050|Async model/photo arrivals that landed during cooperative yields were",
    "CODELORE|city-performance.js|0051|captured by registerLateObject and are now folded into normal chunks.",
    "CODELORE|city-performance.js|0052|Chunks created after the initial freeze (late async assets) are",
    "CODELORE|city-performance.js|0053|identity transforms too, but explicitly freeze/update them because",
    "CODELORE|city-performance.js|0054|scene-wide matrixWorldAutoUpdate is already disabled at that point.",
    "CODELORE|city-performance.js|0055|scene and chunk are both identity transforms",
    "CODELORE|city-performance.js|0056|Copy because placeObject reparents children out of scene.children.",
    "CODELORE|city-performance.js|0057|Everything except explicitly dynamic roots is now immutable. Freeze",
    "CODELORE|city-performance.js|0058|world matrices once, then disable scene-wide automatic matrix updates.",
    "CODELORE|city-performance.js|0059|The renderer otherwise walks every Object3D every frame even if its",
    "CODELORE|city-performance.js|0060|transform has not changed since generation."
]);
