export const CODE_LORE_CONFIG_GAME_CONFIG = Object.freeze([
    "CODELORE|config/game-config.js|0001|DAYTIME. Bright open sky, real sun, long sightlines — the gradient",
    "CODELORE|config/game-config.js|0002|below is still a real duality, just played across daylight instead",
    "CODELORE|config/game-config.js|0003|of a day/night switch: blinding open-plaza glare vs. cooler",
    "CODELORE|config/game-config.js|0004|overcast-alley shade, never full dark.",
    "CODELORE|config/game-config.js|0005|the maze runs along a north/south gradient (grid row, mirrored in",
    "CODELORE|config/game-config.js|0006|world Z) between two poles. Nothing teleports you between them —",
    "CODELORE|config/game-config.js|0007|you walk the gradient continuously, which is the point.",
    "CODELORE|config/game-config.js|0008|south pole (+row/+Z): \"light web\" — oversaturated, over-indexed,",
    "CODELORE|config/game-config.js|0009|loud, blinding noon glare. everything about you is here, which",
    "CODELORE|config/game-config.js|0010|is exactly why none of it is you specifically.",
    "CODELORE|config/game-config.js|0011|north pole (-row/-Z): \"dark web\" — cooler, flatter, overcast —",
    "CODELORE|config/game-config.js|0012|sparser and quieter, never actually dark.",
    "CODELORE|config/game-config.js|0013|Permanent live-world loading policy. These live in CONFIG rather than",
    "CODELORE|config/game-config.js|0014|hard-coded scheduler literals so the existing cfg.* parameter system can",
    "CODELORE|config/game-config.js|0015|tune them on a reload without rewriting the chunk engine.",
    "CODELORE|config/game-config.js|0016|The generic factory builds a complete off-scene chunk in roughly",
    "CODELORE|config/game-config.js|0017|millisecond-scale CPU time on desktop. Keep chunk construction atomic",
    "CODELORE|config/game-config.js|0018|and budget the OUTER pump instead of inserting rAF sleeps inside it.",
    "CODELORE|config/game-config.js|0019|Decorative GLTF work is explicitly non-structural. Requests queue",
    "CODELORE|config/game-config.js|0020|during boot but do not start until the nearby 7x7 structural world",
    "CODELORE|config/game-config.js|0021|is READY, then this small cap prevents network/decode stampedes.",
    "CODELORE|config/game-config.js|0022|\"moon\" is the sun now, high overhead — real directional daylight",
    "CODELORE|config/game-config.js|0023|warm ground-bounce light so alley shade never reads as flat black",
    "CODELORE|config/game-config.js|0024|per-platform render quality. Desktop values are the intended look;",
    "CODELORE|config/game-config.js|0025|mobile trims cost (pixel ratio, bloom, lights, prop count) to hold",
    "CODELORE|config/game-config.js|0026|frame rate on weaker GPUs instead of cutting features outright.",
    "CODELORE|config/game-config.js|0027|Bloom threshold is high on purpose: daylight scenes are bright",
    "CODELORE|config/game-config.js|0028|everywhere, so only genuinely emissive signage should glow, not",
    "CODELORE|config/game-config.js|0029|sunlit concrete.",
    "CODELORE|config/game-config.js|0030|17x17 world-width pass: floor/hero-floor caps are UNCHANGED on",
    "CODELORE|config/game-config.js|0031|purpose (this is a wider-not-taller pass -- see maze.cols/rows",
    "CODELORE|config/game-config.js|0032|below). propDensity is interpolated 60% of the way from the",
    "CODELORE|config/game-config.js|0033|11x11 numbers toward this project's own real historical 21x21",
    "CODELORE|config/game-config.js|0034|numbers (t=(17-11)/(21-11)=0.6) rather than re-derived from",
    "CODELORE|config/game-config.js|0035|scratch -- that's a real prior tuning pass, not a guess. The",
    "CODELORE|config/game-config.js|0036|per-cell multiplier moves DOWN slightly at t=0.6 (2.8 -> 2.5):",
    "CODELORE|config/game-config.js|0037|the map itself now supplies more area, so less artificial",
    "CODELORE|config/game-config.js|0038|per-cell compensation is needed to read as dense.",
    "CODELORE|config/game-config.js|0039|every floor is real/walkable now -- no decorative tower above this cap, just a shorter real building",
    "CODELORE|config/game-config.js|0040|hero towers get a real multi-room stair-core stack",
    "CODELORE|config/game-config.js|0041|auto-selected on low core-count/low-memory machines (touch or",
    "CODELORE|config/game-config.js|0042|not -- see detectWeakGPU below), or forced with ?quality=low.",
    "CODELORE|config/game-config.js|0043|Bloom pass is skipped entirely here, not just turned down --",
    "CODELORE|config/game-config.js|0044|the blur passes have a real GPU cost even at low strength.",
    "CODELORE|config/game-config.js|0045|---------------- maze layout ----------------",
    "CODELORE|config/game-config.js|0046|the whole environment is a grid of building-block cells. Cells are",
    "CODELORE|config/game-config.js|0047|either solid (a building) or open (an alley). A perimeter ring is",
    "CODELORE|config/game-config.js|0048|always solid so the maze is naturally walled in — no invisible clamp.",
    "CODELORE|config/game-config.js|0049|World-width pass: wider again after the 11x11 compression that",
    "CODELORE|config/game-config.js|0050|forced the real-floors/real-stairs/real-facade work. This is",
    "CODELORE|config/game-config.js|0051|~2.4x the 11x11 footprint (about 55% of the way back to the old",
    "CODELORE|config/game-config.js|0052|21x21) -- MORE CITY (more blocks, more routes, more buildings,",
    "CODELORE|config/game-config.js|0053|more room for signature locations to sit apart from each other),",
    "CODELORE|config/game-config.js|0054|not taller buildings: CONFIG.buildings/CONFIG.quality's floor",
    "CODELORE|config/game-config.js|0055|counts are untouched by this change. Stays odd -- the DFS carve",
    "CODELORE|config/game-config.js|0056|below moves in steps of 2, so an odd grid is what keeps the",
    "CODELORE|config/game-config.js|0057|parity/perimeter math clean.",
    "CODELORE|config/game-config.js|0058|The authored spawn district is intentionally compact enough to fit",
    "CODELORE|config/game-config.js|0059|inside logical chunk (0,0). Infinite surrounding chunks provide",
    "CODELORE|config/game-config.js|0060|world scale; startup cost is therefore bounded by this one district.",
    "CODELORE|config/game-config.js|0061|the grid alternates block/street pitch by parity -- but by",
    "CODELORE|config/game-config.js|0062|ROOM topology, not naive index parity: the maze DFS (below)",
    "CODELORE|config/game-config.js|0063|always starts on an (even,even) cell and only ever steps by 2,",
    "CODELORE|config/game-config.js|0064|so every interior (even,even) cell is a visited room, provably",
    "CODELORE|config/game-config.js|0065|ALWAYS open. Every solid (building) cell has at least one odd",
    "CODELORE|config/game-config.js|0066|axis. So streetWidth is handed to EVEN indices (the open",
    "CODELORE|config/game-config.js|0067|rooms/plazas the maze network is built from) and blockSize to",
    "CODELORE|config/game-config.js|0068|ODD indices (the building footprint -- see axisPitch). Naming",
    "CODELORE|config/game-config.js|0069|stays keyed to what each number visually controls, not the",
    "CODELORE|config/game-config.js|0070|literal parity.",
    "CODELORE|config/game-config.js|0071|world units per building footprint (odd row/col)",
    "CODELORE|config/game-config.js|0072|world units per open room/plaza the street network connects through (even row/col) -- real narrow-alley width; see streetSetbackRoll for why this no longer risks a sealed/impassable alley",
    "CODELORE|config/game-config.js|0073|chance a redundant wall opens up into a plaza/loop",
    "CODELORE|config/game-config.js|0074|how much smaller than the cell a building footprint is",
    "CODELORE|config/game-config.js|0075|floor count IS the height now -- there is no more separate",
    "CODELORE|config/game-config.js|0076|world-unit height rolled first with a decorative, walk-through",
    "CODELORE|config/game-config.js|0077|tower filling in whatever didn't fit a \"real\" floor. Every unit",
    "CODELORE|config/game-config.js|0078|of visible height corresponds to a real, walkable, stair-",
    "CODELORE|config/game-config.js|0079|connected floor (see addBuildingModule/buildCoreFloor's",
    "CODELORE|config/game-config.js|0080|continuous stair core). height = floorCount * floorHeight,",
    "CODELORE|config/game-config.js|0081|always, exactly.",
    "CODELORE|config/game-config.js|0082|~8% of buildings are hero buildings -- genuinely more floors",
    "CODELORE|config/game-config.js|0083|(real ones, all the way up), not a taller fake extrusion.",
    "CODELORE|config/game-config.js|0084|daylight facades — light concrete/sandstone/brick tones with",
    "CODELORE|config/game-config.js|0085|green/orange/red/cyan casts. NO black, NO purple, anywhere.",
    "CODELORE|config/game-config.js|0086|light concrete",
    "CODELORE|config/game-config.js|0087|sandstone tan",
    "CODELORE|config/game-config.js|0088|pale sage green",
    "CODELORE|config/game-config.js|0089|mustard tan",
    "CODELORE|config/game-config.js|0090|warm orange-brick",
    "CODELORE|config/game-config.js|0091|muted red-brick",
    "CODELORE|config/game-config.js|0092|pale cyan-gray",
    "CODELORE|config/game-config.js|0093|near-white cream",
    "CODELORE|config/game-config.js|0094|light olive green",
    "CODELORE|config/game-config.js|0095|khaki",
    "CODELORE|config/game-config.js|0096|how far the curb/base skirt extends past the facade",
    "CODELORE|config/game-config.js|0097|---------------- signature locations ----------------",
    "CODELORE|config/game-config.js|0098|Five authored \"micro-levels\" embedded in the procedural city: a",
    "CODELORE|config/game-config.js|0099|recognizable footprint, a deliberate room graph, real content --",
    "CODELORE|config/game-config.js|0100|built from the SAME wall/floor/facade/stair primitives generic",
    "CODELORE|config/game-config.js|0101|buildings use (see SIGNATURE_BUILDERS near reserveSignatureSites),",
    "CODELORE|config/game-config.js|0102|not a generic building wearing a special sign. Location is",
    "CODELORE|config/game-config.js|0103|procedural (reserveSignatureSites picks WHERE, before generic",
    "CODELORE|config/game-config.js|0104|BuildingSites are assembled -- see assembleBuildingSites); identity",
    "CODELORE|config/game-config.js|0105|and room graph are authored per builder function, not re-rolled.",
    "CODELORE|config/game-config.js|0106|Debug: ?debugSignatures=1 overlays every reserved site + its",
    "CODELORE|config/game-config.js|0107|entrances; ?landmark=<key> (artGallery/as400Archive/justinIndex/",
    "CODELORE|config/game-config.js|0108|systemsWorkshop/loreShrine) spawns just outside that site's main",
    "CODELORE|config/game-config.js|0109|entrance instead of a random maze cell.",
    "CODELORE|config/game-config.js|0110|Chebyshev cell distance between ANY two signatures' member",
    "CODELORE|config/game-config.js|0111|cells -- keeps them from landing shoulder-to-shoulder on",
    "CODELORE|config/game-config.js|0112|one block. The authored district is intentionally compact; all",
    "CODELORE|config/game-config.js|0113|singulars stay near the centered spawn while the infinite chunk",
    "CODELORE|config/game-config.js|0114|substrate supplies scale outside this neighborhood.",
    "CODELORE|config/game-config.js|0115|All authored world-singular content belongs to the spawn district.",
    "CODELORE|config/game-config.js|0116|The rest of the world is ordinary coordinate-addressed procedural",
    "CODELORE|config/game-config.js|0117|space, so uniqueness never becomes a distributed-generation problem.",
    "CODELORE|config/game-config.js|0118|>=1 site cell must be adjacent to a real open (alley/street) cell",
    "CODELORE|config/game-config.js|0119|and a second, independent open-adjacent edge, logged (not hard-failed) if the site's too small/pinched to have one",
    "CODELORE|config/game-config.js|0120|per signature, before giving up and disabling just that one this load -- never silently squeezed into an invalid spot",
    "CODELORE|config/game-config.js|0121|targetCells: [min,max] site size in cells, same unit",
    "CODELORE|config/game-config.js|0122|SITE_SIZE_WEIGHTS/assembleBuildingSites already uses.",
    "CODELORE|config/game-config.js|0123|preferredFloors feeds the placeholder massing AND (once each",
    "CODELORE|config/game-config.js|0124|builder lands) its real floor plan -- see per-builder TODOs.",
    "CODELORE|config/game-config.js|0125|the Four Button Chamber's centerpiece -- exactly 4, no",
    "CODELORE|config/game-config.js|0126|fifth-button joke unless this array itself grows one.",
    "CODELORE|config/game-config.js|0127|white / yellow / green / orange / red / cyan — the full signage",
    "CODELORE|config/game-config.js|0128|palette. NO black, NO purple. In daylight these read as painted",
    "CODELORE|config/game-config.js|0129|signage rather than glowing neon, which is fine — the color logic",
    "CODELORE|config/game-config.js|0130|(warm toward light-web, cool toward dark-web) still carries the",
    "CODELORE|config/game-config.js|0131|gradient regardless of what time of day it's rendered as.",
    "CODELORE|config/game-config.js|0132|every commonly-nameable color, not a restricted subset -- signage",
    "CODELORE|config/game-config.js|0133|is neon, and real neon comes in every hue there is.",
    "CODELORE|config/game-config.js|0134|white",
    "CODELORE|config/game-config.js|0135|silver",
    "CODELORE|config/game-config.js|0136|gray",
    "CODELORE|config/game-config.js|0137|black (bare-bulb-off look, reads on a lit sign frame)",
    "CODELORE|config/game-config.js|0138|yellow",
    "CODELORE|config/game-config.js|0139|gold",
    "CODELORE|config/game-config.js|0140|amber/brass",
    "CODELORE|config/game-config.js|0141|green",
    "CODELORE|config/game-config.js|0142|lime",
    "CODELORE|config/game-config.js|0143|dark green",
    "CODELORE|config/game-config.js|0144|cyan",
    "CODELORE|config/game-config.js|0145|light cyan",
    "CODELORE|config/game-config.js|0146|teal",
    "CODELORE|config/game-config.js|0147|blue",
    "CODELORE|config/game-config.js|0148|navy",
    "CODELORE|config/game-config.js|0149|purple",
    "CODELORE|config/game-config.js|0150|indigo",
    "CODELORE|config/game-config.js|0151|magenta",
    "CODELORE|config/game-config.js|0152|pink",
    "CODELORE|config/game-config.js|0153|light pink",
    "CODELORE|config/game-config.js|0154|orange",
    "CODELORE|config/game-config.js|0155|light orange",
    "CODELORE|config/game-config.js|0156|brown",
    "CODELORE|config/game-config.js|0157|red",
    "CODELORE|config/game-config.js|0158|light red",
    "CODELORE|config/game-config.js|0159|maroon",
    "CODELORE|config/game-config.js|0160|same colors, split by temperature so signage can lean warm toward",
    "CODELORE|config/game-config.js|0161|the light-web pole and cool toward the dark-web pole.",
    "CODELORE|config/game-config.js|0162|---------------- real-world data ----------------",
    "CODELORE|config/game-config.js|0163|not synthetic noise — actual sourced numbers, fetched live and baked",
    "CODELORE|config/game-config.js|0164|in rather than called from the browser at runtime (a live third-party",
    "CODELORE|config/game-config.js|0165|API is a fragile thing to hang a visitor's page on). Everything here",
    "CODELORE|config/game-config.js|0166|is real; nothing is invented to look real.",
    "CODELORE|config/game-config.js|0167|DJIA year-end close, 1950-2025, SEC-filed historical table (via",
    "CODELORE|config/game-config.js|0168|researched/verified public data, 2026-08-27). Full annual series",
    "CODELORE|config/game-config.js|0169|now, not just milestone crossings — real recessions (1973-74,",
    "CODELORE|config/game-config.js|0170|2000-02, 2008) and real bull runs are actual shape in the line,",
    "CODELORE|config/game-config.js|0171|not decoration. This drives the \"crack in the concrete\" texture.",
    "CODELORE|config/game-config.js|0172|Real elevations in feet (researched/verified public data,",
    "CODELORE|config/game-config.js|0173|2026-08-27): the actual Pacific Crest Trail transect through",
    "CODELORE|config/game-config.js|0174|Washington (Bridge of the Gods to the Canadian border, 36 real",
    "CODELORE|config/game-config.js|0175|waypoints), plus Illinois' real range as the flat, ordinary",
    "CODELORE|config/game-config.js|0176|literal center of this whole project (SIU Carbondale, College",
    "CODELORE|config/game-config.js|0177|of DuPage — his actual home ground), plus world extremes at",
    "CODELORE|config/game-config.js|0178|both ends. Illinois: mean 590ft, a 956ft total range statewide",
    "CODELORE|config/game-config.js|0179|— genuinely close to flat next to a real trail that swings",
    "CODELORE|config/game-config.js|0180|from 200ft to 6,800ft.",
    "CODELORE|config/game-config.js|0181|real Historic Route 66 itinerary, Chicago (its historic eastern",
    "CODELORE|config/game-config.js|0182|terminus, Grant Park) through Illinois to the Mississippi",
    "CODELORE|config/game-config.js|0183|crossing -- researched/verified public data, 2026-08-27.",
    "CODELORE|config/game-config.js|0184|Transportation infrastructure, for real, drives the mile-marker",
    "CODELORE|config/game-config.js|0185|signage scattered through the maze.",
    "CODELORE|config/game-config.js|0186|shape/font/border/backing are rolled per-sign now (see",
    "CODELORE|config/game-config.js|0187|SIGN_SHAPES etc. near addSign) instead of one fixed look",
    "CODELORE|config/game-config.js|0188|shared by every sign in the city.",
    "CODELORE|config/game-config.js|0189|decorative back-alley market / red-light flavor signage — pure texture",
    "CODELORE|config/game-config.js|0190|the curated list above is hand-picked; everything past this",
    "CODELORE|config/game-config.js|0191|point is a base cross-join of shop noun x tagline. At render time",
    "CODELORE|config/game-config.js|0192|pickRandomizedCuratedPair() can splice these with the large poetry",
    "CODELORE|config/game-config.js|0193|corpus, so this list is vocabulary now rather than final copy.",
    "CODELORE|config/game-config.js|0194|the whole reason this is a maze: real Census (2020, surname",
    "CODELORE|config/game-config.js|0195|\"Brown\" = rank 4, 1,386,083 people) and SSA (first name",
    "CODELORE|config/game-config.js|0196|\"Justin\") frequency data combine to an estimated 3,529 living",
    "CODELORE|config/game-config.js|0197|Americans named exactly \"Justin Brown\" (~1 in 97,125) —",
    "CODELORE|config/game-config.js|0198|researched/verified public data, 2026-08-27, not invented for",
    "CODELORE|config/game-config.js|0199|effect. Every decoy below is one of them, queryable, none of",
    "CODELORE|config/game-config.js|0200|them him.",
    "CODELORE|config/game-config.js|0201|the site itself talking back — the machinery of search admitting",
    "CODELORE|config/game-config.js|0202|it came up short, or asking you to keep paying for the privilege.",
    "CODELORE|config/game-config.js|0203|base cross-join; runtime system-sign picks are remixed with the poetry corpus",
    "CODELORE|config/game-config.js|0204|exactly one of these exists, at the farthest dead end from",
    "CODELORE|config/game-config.js|0205|spawn. everything else in the city is noise wearing his name.",
    "CODELORE|config/game-config.js|0206|tabloid front pages for the newsstand prop — pure comic relief,",
    "CODELORE|config/game-config.js|0207|still on-theme (the search-for-one-guy joke, played for laughs).",
    "CODELORE|config/game-config.js|0208|near-misses — styled close enough to the real signal to make you",
    "CODELORE|config/game-config.js|0209|check twice, planted at the 2nd/3rd farthest dead ends. The",
    "CODELORE|config/game-config.js|0210|public secret only works if the almost-right answers are",
    "CODELORE|config/game-config.js|0211|genuinely tempting, not obviously fake.",
    "CODELORE|config/game-config.js|0212|relative odds a given sign face pulls from each bucket — nav",
    "CODELORE|config/game-config.js|0213|pages run out fast on purpose, so decoys and noise dominate.",
    "CODELORE|config/game-config.js|0214|pulled directly from the real jweb.dev content (index.html) — the",
    "CODELORE|config/game-config.js|0215|maze isn't just mood-boarding \"Justin Brown,\" it's built out of the",
    "CODELORE|config/game-config.js|0216|actual resume/projects/art. ~35 entries across 7 categories, each",
    "CODELORE|config/game-config.js|0217|rendered by one of 5 dedicated generator archetypes below.",
    "CODELORE|config/game-config.js|0218|technical builds — rendered as glowing terminal/CRT plaques",
    "CODELORE|config/game-config.js|0219|client/design work — rendered as framed wall posters",
    "CODELORE|config/game-config.js|0220|rhetoric fragments — half bio, half the concept itself",
    "CODELORE|config/game-config.js|0221|real photos, not renders/paintings -- rendered the same way as",
    "CODELORE|config/game-config.js|0222|art/webProjects (see mountContentCards + PHOTO_BY_TITLE), just",
    "CODELORE|config/game-config.js|0223|kept in their own category since they're personal snapshots,",
    "CODELORE|config/game-config.js|0224|not finished pieces or client work.",
    "CODELORE|config/game-config.js|0225|dropped on the ground like litter — real contact info, decoyed",
    "CODELORE|config/game-config.js|0226|among all the fake ones from billboards.decoyIdentities",
    "CODELORE|config/game-config.js|0227|relative spawn weight per alley cell — higher = more common.",
    "CODELORE|config/game-config.js|0228|\"none\" kept low on purpose: dense, high-frequency clutter.",
    "CODELORE|config/game-config.js|0229|rarer -- a real per-frame update, not free like a static sign",
    "CODELORE|config/game-config.js|0230|bumped -- 1 in 5 of these now carries a real personal fact, not just a wiki rabbit hole",
    "CODELORE|config/game-config.js|0231|turned down further -- almost nothing gets to be empty",
    "CODELORE|config/game-config.js|0232|17x17 pass: interpolated the same 60%-toward-the-old-21x21-",
    "CODELORE|config/game-config.js|0233|numbers way as CONFIG.quality's propDensity (see there) --",
    "CODELORE|config/game-config.js|0234|there's a genuinely bigger plazaCells pool to draw from now,",
    "CODELORE|config/game-config.js|0235|but \"special encounter\" counts are",
    "CODELORE|config/game-config.js|0236|exactly the category that should scale slower than raw area",
    "CODELORE|config/game-config.js|0237|(more of these than 11x11 had, nowhere near proportional to the",
    "CODELORE|config/game-config.js|0238|~2.4x area gain). These still draw from the same plazaCells pool",
    "CODELORE|config/game-config.js|0239|in this fixed order, so an early category (statues,",
    "CODELORE|config/game-config.js|0240|constructionZones...) can still starve a later one out of a",
    "CODELORE|config/game-config.js|0241|plaza if the pool runs dry -- just less likely now that there's",
    "CODELORE|config/game-config.js|0242|more pool to begin with.",
    "CODELORE|config/game-config.js|0243|every 4th row/col that's actually open becomes a through-street",
    "CODELORE|config/game-config.js|0244|instead of a back alley -- wider-feeling, cleaner, real sidewalks",
    "CODELORE|config/game-config.js|0245|along the building faces. Everything else stays alley: grimier,",
    "CODELORE|config/game-config.js|0246|denser, no sidewalk distinction. Real cities have both; this",
    "CODELORE|config/game-config.js|0247|shouldn't be maze-wide uniform pavement.",
    "CODELORE|config/game-config.js|0248|streets are thoroughfares, not clutter bins",
    "CODELORE|config/game-config.js|0249|slower than before — cramped alleys, not a sprint",
    "CODELORE|config/game-config.js|0250|hold Shift -- covers real ground, matters for clearing a gap jump",
    "CODELORE|config/game-config.js|0251|notably faster look — this was the #1 complaint"
]);
