export const CODE_LORE_CONTENT_WANTED_CONTENT = Object.freeze([
    "CODELORE|content/wanted-content.js|0001|a real fissure in the pavement, dropped as ground clutter — pulls",
    "CODELORE|content/wanted-content.js|0002|straight from makeCrackTexture rather than a synthetic crack pattern.",
    "CODELORE|content/wanted-content.js|0003|\"wanted\" posters for random Wikipedia rabbit holes -- a real 3am-",
    "CODELORE|content/wanted-content.js|0004|wikipedia-spiral joke. Static fallback (real, verifiably-existing",
    "CODELORE|content/wanted-content.js|0005|article titles) placed immediately at layout time; live random",
    "CODELORE|content/wanted-content.js|0006|articles from Wikipedia's public REST API (CORS-enabled, no key",
    "CODELORE|content/wanted-content.js|0007|needed) swap into already-placed posters as they resolve -- fails",
    "CODELORE|content/wanted-content.js|0008|silently and keeps the static fallback if offline/blocked, same",
    "CODELORE|content/wanted-content.js|0009|\"never hang the page on a live third-party call\" principle as",
    "CODELORE|content/wanted-content.js|0010|everywhere else here, just applied to a decoration instead of core",
    "CODELORE|content/wanted-content.js|0011|content so a network hiccup costs nothing.",
    "CODELORE|content/wanted-content.js|0012|real biographical fragments, styled and shuffled into the exact same",
    "CODELORE|content/wanted-content.js|0013|pool as the Wikipedia rabbit holes above -- on purpose. The whole maze",
    "CODELORE|content/wanted-content.js|0014|runs on the idea that the one true signal shouldn't structurally stand",
    "CODELORE|content/wanted-content.js|0015|out from the noise around it, so these don't get a special frame, a",
    "CODELORE|content/wanted-content.js|0016|special mount, or a special anything: just another wanted poster",
    "CODELORE|content/wanted-content.js|0017|somebody happened to also be right about, indistinguishable from a",
    "CODELORE|content/wanted-content.js|0018|hundred that aren't. Never pushed into wantedPosterMeshes below (see",
    "CODELORE|content/wanted-content.js|0019|addWantedPoster) -- these are real, so they don't get overwritten by",
    "CODELORE|content/wanted-content.js|0020|the live Wikipedia swap the way the fallback fodder does.",
    "CODELORE|content/wanted-content.js|0021|straight out of his own self-mythology (The Great Book of 8gH) --",
    "CODELORE|content/wanted-content.js|0022|same in-voice absurdism as the facts above, just further out.",
    "CODELORE|content/wanted-content.js|0023|same self-mythology, a different obsession -- home-AI-rig tinkering,",
    "CODELORE|content/wanted-content.js|0024|scrambled from lore/personal_infra_vocab_lore.md (gitignored,",
    "CODELORE|content/wanted-content.js|0025|never committed; see INFRA_LORE_FRAGMENTS below for the full pool).",
    "CODELORE|content/wanted-content.js|0026|tagline pairs for the generic (non-personal) wanted poster -- picked per",
    "CODELORE|content/wanted-content.js|0027|poster instead of one fixed pair everywhere, so the wall of them doesn't",
    "CODELORE|content/wanted-content.js|0028|read as a single photocopy repeated over and over.",
    "CODELORE|content/wanted-content.js|0029|the six hand-written pairs above paired one subject with one fixed",
    "CODELORE|content/wanted-content.js|0030|reward each; cross-joining a bigger subject/reward pool the same",
    "CODELORE|content/wanted-content.js|0031|way GRAFFITI_TAGS and CONFIG.billboards.flavorWords already do",
    "CODELORE|content/wanted-content.js|0032|turns 6 into 150 without writing 144 more jokes by hand."
]);
