export const CODE_LORE_CONTENT_SIGNATURE_CONTENT = Object.freeze([
    "CODELORE|content/signature-content.js|0001|============================================================",
    "CODELORE|content/signature-content.js|0002|ART GALLERY -- authored signature location #1.",
    "CODELORE|content/signature-content.js|0003|============================================================",
    "CODELORE|content/signature-content.js|0004|Real content only -- every entry is drawn straight from",
    "CODELORE|content/signature-content.js|0005|CONFIG.siteContent.art/webProjects (already in this repo) and",
    "CODELORE|content/signature-content.js|0006|PHOTO_BY_TITLE; aspectRatio is measured directly from the actual jpg",
    "CODELORE|content/signature-content.js|0007|in vendor/photos (`python3 -c \"from PIL import Image; ...\"`, not",
    "CODELORE|content/signature-content.js|0008|guessed). Nothing here is invented. 'GARY FISCHER' inherits the",
    "CODELORE|content/signature-content.js|0009|project's own pre-existing (slightly odd) PHOTO_BY_TITLE mapping to",
    "CODELORE|content/signature-content.js|0010|the 'bike' photo -- that mapping already existed before this pass;",
    "CODELORE|content/signature-content.js|0011|this catalog reports it faithfully rather than silently \"fixing\" it",
    "CODELORE|content/signature-content.js|0012|into a fact nobody actually asserted.",
    "CODELORE|content/signature-content.js|0013|aspectRatio = height/width, measured directly off the real jpg",
    "CODELORE|content/signature-content.js|0014|(Pillow: Image.open(f).size), same convention buildGalleryArtPanel's",
    "CODELORE|content/signature-content.js|0015|own img.height/img.width uses -- known ahead of the image's own",
    "CODELORE|content/signature-content.js|0016|(async, network) load, which is what lets mountGalleryPiece reserve",
    "CODELORE|content/signature-content.js|0017|real facade space synchronously during layout instead of guessing a",
    "CODELORE|content/signature-content.js|0018|placeholder box and hoping the real image comes in the same shape.",
    "CODELORE|content/signature-content.js|0019|the one piece with no backing photo (see PHOTO_BY_TITLE) -- a real",
    "CODELORE|content/signature-content.js|0020|sculpture, displayed the way a sculpture actually is (pedestal +",
    "CODELORE|content/signature-content.js|0021|placard), not forced into a wall frame it doesn't have a photo for.",
    "CODELORE|content/signature-content.js|0022|============================================================",
    "CODELORE|content/signature-content.js|0023|AS/400 ARCHIVE -- authored signature location #2.",
    "CODELORE|content/signature-content.js|0024|============================================================",
    "CODELORE|content/signature-content.js|0025|PUBLIC TECHNICAL KNOWLEDGE ONLY -- every fact below is well-documented",
    "CODELORE|content/signature-content.js|0026|public IBM i/AS-400 platform history and terminology (product",
    "CODELORE|content/signature-content.js|0027|lineage, CL command names, architecture concepts). None of it is",
    "CODELORE|content/signature-content.js|0028|company-specific, none of it is credentials/internal-systems/GAL",
    "CODELORE|content/signature-content.js|0029|implementation detail -- this is a public website.",
    "CODELORE|content/signature-content.js|0030|real product lineage -- System/38's single-level-store/integrated-",
    "CODELORE|content/signature-content.js|0031|database architecture is the actual throughline every rename since",
    "CODELORE|content/signature-content.js|0032|has kept running underneath.",
    "CODELORE|content/signature-content.js|0033|CL commands -- real, well-known, generic (never a company's actual",
    "CODELORE|content/signature-content.js|0034|job/library/object names).",
    "CODELORE|content/signature-content.js|0035|architecture/object-model concepts -- the library/object system,",
    "CODELORE|content/signature-content.js|0036|languages, and runtime vocabulary. Real terminology, generic",
    "CODELORE|content/signature-content.js|0037|definitions."
]);
