export const CODE_LORE_CONTENT_LORE_FRAGMENTS = Object.freeze([
    "CODELORE|content/lore-fragments.js|0001|mythology fragments — the same absurdist personal canon (The Great",
    "CODELORE|content/lore-fragments.js|0002|Book of 8gH) that the graffiti/wanted-poster pools quote from, cut",
    "CODELORE|content/lore-fragments.js|0003|down to sticker-flyer length. Kept separate from siteContent (real",
    "CODELORE|content/lore-fragments.js|0004|resume/portfolio facts) so this stays clearly its own decorative genre.",
    "CODELORE|content/lore-fragments.js|0005|curated above; title x domain combinations below remain useful base",
    "CODELORE|content/lore-fragments.js|0006|vocabulary, but runtime lore picks now splice them with the already-built",
    "CODELORE|content/lore-fragments.js|0007|poetry corpus. Reproducible text is intentionally not a goal anymore.",
    "CODELORE|content/lore-fragments.js|0008|a second self-mythology voice, distilled the same way as the 8gH pool",
    "CODELORE|content/lore-fragments.js|0009|above: semantically-scrambled derivative flavor text, jumbled on",
    "CODELORE|content/lore-fragments.js|0010|purpose from private working notes (`lore/personal_infra_vocab_lore.md`,",
    "CODELORE|content/lore-fragments.js|0011|gitignored, never committed -- only this transformed output ships).",
    "CODELORE|content/lore-fragments.js|0012|No real names/hosts/IPs/employers survive; this is a home-AI-tinkerer",
    "CODELORE|content/lore-fragments.js|0013|self-mythology register (rigs, borrowed compute, the ghost-in-the-jar),",
    "CODELORE|content/lore-fragments.js|0014|same personal-canon spirit as 8gH, just a different obsession.",
    "CODELORE|content/lore-fragments.js|0015|cross-join for base vocabulary; runtime lore picks mutate these with",
    "CODELORE|content/lore-fragments.js|0016|unseeded shards from the poetry corpus.",
    "CODELORE|content/lore-fragments.js|0017|a third voice: institutional-legacy-tech-support folklore, distilled",
    "CODELORE|content/lore-fragments.js|0018|from `lore/support_vocab_lore.md` (gitignored, never committed) the",
    "CODELORE|content/lore-fragments.js|0019|same way as the two pools above. Deliberately NOT personal -- this is",
    "CODELORE|content/lore-fragments.js|0020|in-universe city lore about a \"half-forgotten legacy tech-support",
    "CODELORE|content/lore-fragments.js|0021|caste,\" kept clearly separate from AS400_CONTENT's real/factual IBM i",
    "CODELORE|content/lore-fragments.js|0022|terminology so a reader never confuses fiction with the real archive.",
    "CODELORE|content/lore-fragments.js|0023|cross-join for base vocabulary; runtime lore picks mutate these with",
    "CODELORE|content/lore-fragments.js|0024|unseeded shards from the poetry corpus."
]);
