export const CODE_LORE_INFINITE_CITY_CHUNKS = Object.freeze([
    "CODELORE|infinite-city-chunks.js|0001|Infinite procedural city substrate.",
    "CODELORE|infinite-city-chunks.js|0002|Chunk 0,0 is the authored spawn district and is never rebuilt here. Every",
    "CODELORE|infinite-city-chunks.js|0003|other coordinate is independently reproducible from (worldSeed, chunkX,",
    "CODELORE|infinite-city-chunks.js|0004|chunkZ). Neighboring chunks share deterministic road-portal contracts at",
    "CODELORE|infinite-city-chunks.js|0005|their common boundary, but everything inside the boundary is locally owned",
    "CODELORE|infinite-city-chunks.js|0006|and disposable.",
    "CODELORE|infinite-city-chunks.js|0007|Shared-edge road contract. The canonical edge key is identical from",
    "CODELORE|infinite-city-chunks.js|0008|either neighboring chunk, so generation order never affects where the",
    "CODELORE|infinite-city-chunks.js|0009|opening lands. One full micro-cell is the cross-boundary gate.",
    "CODELORE|infinite-city-chunks.js|0010|The authored spawn district exposes four centered cardinal streets.",
    "CODELORE|infinite-city-chunks.js|0011|Force the four shared boundaries touching chunk 0,0 to the matching",
    "CODELORE|infinite-city-chunks.js|0012|center lane; all other edges remain hash-addressed and irregular.",
    "CODELORE|infinite-city-chunks.js|0013|A few deterministic local alleys/loops keep interiors from reducing",
    "CODELORE|infinite-city-chunks.js|0014|to four L-shaped spokes. Weirdness can increase this later without",
    "CODELORE|infinite-city-chunks.js|0015|changing the boundary contract or world format.",
    "CODELORE|infinite-city-chunks.js|0016|Door is a visible panel inside the real collision opening.",
    "CODELORE|infinite-city-chunks.js|0017|Cheap instanced windows keep streamed districts legible as actual",
    "CODELORE|infinite-city-chunks.js|0018|buildings without introducing per-window materials or draw calls.",
    "CODELORE|infinite-city-chunks.js|0019|Every occupied floor has a real stair to the next support level;",
    "CODELORE|infinite-city-chunks.js|0020|the final flight reaches a NOTCHED roof instead of terminating at",
    "CODELORE|infinite-city-chunks.js|0021|an invisible ceiling.",
    "CODELORE|infinite-city-chunks.js|0022|Exactly one disposable/repeatable landmark chunk is selected inside each",
    "CODELORE|infinite-city-chunks.js|0023|macro-cell. This gives the infinite city recurring authored-scale visual",
    "CODELORE|infinite-city-chunks.js|0024|anchors without introducing any new world-singular state. The selection",
    "CODELORE|infinite-city-chunks.js|0025|is coordinate deterministic, so unloading/revisiting never moves it.",
    "CODELORE|infinite-city-chunks.js|0026|Landmark crowns reuse the same instanced wall batch as ordinary",
    "CODELORE|infinite-city-chunks.js|0027|buildings, so recurrence adds visual hierarchy without creating a",
    "CODELORE|infinite-city-chunks.js|0028|per-landmark draw-call tax. Roof-level collision is explicit.",
    "CODELORE|infinite-city-chunks.js|0029|Canonical ownership: each chunk owns only EAST and SOUTH edges.",
    "CODELORE|infinite-city-chunks.js|0030|Neighboring west/north edges therefore never double-render the same",
    "CODELORE|infinite-city-chunks.js|0031|barrier. The one road-portal cell remains open.",
    "CODELORE|infinite-city-chunks.js|0032|Prefetched chunks are structurally complete but stay hidden until the",
    "CODELORE|infinite-city-chunks.js|0033|streamer says they are inside its render ring. No other visibility",
    "CODELORE|infinite-city-chunks.js|0034|system is allowed to own this root.",
    "CODELORE|infinite-city-chunks.js|0035|One canonical low wall around non-road chunk seams turns the shared",
    "CODELORE|infinite-city-chunks.js|0036|portal layout into a real traversable contract instead of merely a",
    "CODELORE|infinite-city-chunks.js|0037|pavement texture. It also gives the infinite city a maze-like edge.",
    "CODELORE|infinite-city-chunks.js|0038|Infinite chunks bypass scene.add() on purpose. main.js intercepts",
    "CODELORE|infinite-city-chunks.js|0039|ordinary scene.add calls for legacy spawn-district optimization; a",
    "CODELORE|infinite-city-chunks.js|0040|streamed root must never be re-parented, re-chunked, frozen or hidden",
    "CODELORE|infinite-city-chunks.js|0041|by that older system. WorldChunkStreamer is the sole render owner.",
    "CODELORE|infinite-city-chunks.js|0042|All GPU geometries/materials are shared factory resources. Clearing",
    "CODELORE|infinite-city-chunks.js|0043|the root releases only this chunk's Object3D + instance-matrix data;",
    "CODELORE|infinite-city-chunks.js|0044|physics ownership is deactivated/compacted independently."
]);
