export const CODE_LORE_PLAYER_PHYSICS = Object.freeze([
    "CODELORE|player-physics.js|0001|@quantitative-parameterized -- generated; edit build-parameter-catalog.cjs to rebuild",
    "CODELORE|player-physics.js|0002|Player physics for the procedural city.",
    "CODELORE|player-physics.js|0003|The world deliberately has a lot of overlapping vertical structure:",
    "CODELORE|player-physics.js|0004|roofs, floor plates, mezzanines, ramps, ladders, props, and floor-banded",
    "CODELORE|player-physics.js|0005|wall segments. Treating movement as \"move once, then push out\" makes the",
    "CODELORE|player-physics.js|0006|result frame-rate dependent and lets unrelated geometry eject the player.",
    "CODELORE|player-physics.js|0007|This controller instead advances the same motion through small substeps,",
    "CODELORE|player-physics.js|0008|validates a complete standing body at each candidate pose, and rejects or",
    "CODELORE|player-physics.js|0009|slides blocked horizontal movement. It never resolves penetration by",
    "CODELORE|player-physics.js|0010|searching for an arbitrary escape direction or by moving the player's feet",
    "CODELORE|player-physics.js|0011|below the support surface.",
    "CODELORE|player-physics.js|0012|Static + append-only broadphase. The controller may now be created as",
    "CODELORE|player-physics.js|0013|soon as the first streamed world chunk is committed. Existing geometry",
    "CODELORE|player-physics.js|0014|is indexed once here and syncDynamicWorld() extends the same indexes as",
    "CODELORE|player-physics.js|0015|later chunks arrive, so no full-city rebuild is required.",
    "CODELORE|player-physics.js|0016|Nested numeric Maps avoid allocating an \"ix,iz\" string for every",
    "CODELORE|player-physics.js|0017|broadphase lookup. At high FPS the solver performs many queries per",
    "CODELORE|player-physics.js|0018|render frame, so this tiny allocation used to show up surprisingly",
    "CODELORE|player-physics.js|0019|quickly once the world got large enough to make GC more frequent.",
    "CODELORE|player-physics.js|0020|If a synthetic ladder sample and a real slab share the same",
    "CODELORE|player-physics.js|0021|height, prefer the real slab so the top landing behaves like a",
    "CODELORE|player-physics.js|0022|landing rather than remaining in ladder-climb mode.",
    "CODELORE|player-physics.js|0023|Ladder climb points are support-only samples, not physical slabs.",
    "CODELORE|player-physics.js|0024|Existing platform entries default to solid for backwards compatibility.",
    "CODELORE|player-physics.js|0025|Convert the generation-time string-keyed map to a direct row/column",
    "CODELORE|player-physics.js|0026|lookup once. Physics asks for the surrounding 3x3 cells many times per",
    "CODELORE|player-physics.js|0027|substep; constructing nine `${r},${c}` strings each time is needless.",
    "CODELORE|player-physics.js|0028|Large worlds can now decorate distant sectors after play has already",
    "CODELORE|player-physics.js|0029|started. Generation collections stay append-only, so extending the",
    "CODELORE|player-physics.js|0030|broadphase is O(number of newly generated items), never a full rebuild.",
    "CODELORE|player-physics.js|0031|This is deliberately explicit rather than observing Array.push(): one",
    "CODELORE|player-physics.js|0032|sector batch can add hundreds of pieces and pays one cheap sync at the end.",
    "CODELORE|player-physics.js|0033|Infinite/chunk-owned collision data. These records never depend on the",
    "CODELORE|player-physics.js|0034|finite spawn-grid row/column map: a streamed chunk can register its own",
    "CODELORE|player-physics.js|0035|local collision primitives, deactivate them on unload, and reactivate",
    "CODELORE|player-physics.js|0036|the exact same deterministic records when revisited.",
    "CODELORE|player-physics.js|0037|Rebuild the five streamed broadphase maps from the permanent authored",
    "CODELORE|player-physics.js|0038|arrays plus CURRENTLY resident chunk owners. This is intentionally rare",
    "CODELORE|player-physics.js|0039|and bounded: unloads are cheap flag flips; after enough dead owners have",
    "CODELORE|player-physics.js|0040|accumulated, one compaction makes every collider from forgotten chunks",
    "CODELORE|player-physics.js|0041|garbage-collectable instead of retaining an invisible travel history.",
    "CODELORE|player-physics.js|0042|Progressive generation exposes a chunk only after its render objects",
    "CODELORE|player-physics.js|0043|and collision additions have committed. Treat an uncommitted chunk",
    "CODELORE|player-physics.js|0044|as a temporary hard frontier instead of allowing the capsule to walk",
    "CODELORE|player-physics.js|0045|into a solid cell whose real wall mesh/collider does not exist yet.",
    "CODELORE|player-physics.js|0046|Used only before the controller has ever observed a valid pose (normally",
    "CODELORE|player-physics.js|0047|just a pathological procedural spawn). Runtime collision never performs",
    "CODELORE|player-physics.js|0048|this search: once play starts, invalid motion rolls back to the previous",
    "CODELORE|player-physics.js|0049|valid pose instead of picking a new escape direction.",
    "CODELORE|player-physics.js|0050|Ladder samples are intentionally stacked at the same X/Z. Without",
    "CODELORE|player-physics.js|0051|a time-based cap, render substepping would climb one sample PER",
    "CODELORE|player-physics.js|0052|SUBSTEP and a low-FPS frame would shoot up the ladder. Treat the",
    "CODELORE|player-physics.js|0053|samples as a continuous climb guide with a real units/second rate.",
    "CODELORE|player-physics.js|0054|Consume buffered jump before aging the timers. This makes a jump",
    "CODELORE|player-physics.js|0055|request independent of whether this render frame happened to be",
    "CODELORE|player-physics.js|0056|split into one physics substep or twelve.",
    "CODELORE|player-physics.js|0057|A solver bug or malformed procedural geometry is allowed to stop a",
    "CODELORE|player-physics.js|0058|move, never to invent a new vertical escape route. First restore the",
    "CODELORE|player-physics.js|0059|substep start; only fall back to the older safe pose if the start was",
    "CODELORE|player-physics.js|0060|already invalid (for example after leaving freecam inside geometry).",
    "CODELORE|player-physics.js|0061|Synchronization asks \"what am I already standing on?\", not",
    "CODELORE|player-physics.js|0062|\"what could I auto-step onto next?\". Using the ordinary step",
    "CODELORE|player-physics.js|0063|query here made spawning beside a ladder silently start one rung",
    "CODELORE|player-physics.js|0064|up because that rung happened to be within MAX_STEP_HEIGHT.",
    "CODELORE|player-physics.js|0065|Initial state should reflect the actual spawn/support surface rather",
    "CODELORE|player-physics.js|0066|than assuming y=0 forever. This matters for ?landmark= and future",
    "CODELORE|player-physics.js|0067|spawn points placed on upper floors."
]);
