export const CODE_LORE_WORLD_CHUNK_STREAMER = Object.freeze([
    "CODELORE|world-chunk-streamer.js|0001|Coordinate-addressed world streaming core.",
    "CODELORE|world-chunk-streamer.js|0002|The world is not a boot phase. A chunk is the atomic unit of reality:",
    "CODELORE|world-chunk-streamer.js|0003|planned -> queued -> building -> committing -> ready -> unloading -> unloaded.",
    "CODELORE|world-chunk-streamer.js|0004|The spawn chunk is the only startup gate. Everything else is selected by",
    "CODELORE|world-chunk-streamer.js|0005|player distance and can be discarded/rebuilt deterministically.",
    "CODELORE|world-chunk-streamer.js|0006|Distance stays dominant. Heading only breaks/softens ties so the",
    "CODELORE|world-chunk-streamer.js|0007|browser tends to finish the world the player is actually looking or",
    "CODELORE|world-chunk-streamer.js|0008|moving toward before equally-near chunks behind them.",
    "CODELORE|world-chunk-streamer.js|0009|A generic chunk is intentionally atomic. The factory builds it",
    "CODELORE|world-chunk-streamer.js|0010|off-scene, normally in only a few milliseconds, then this method",
    "CODELORE|world-chunk-streamer.js|0011|publishes visuals + physics together. Do NOT force an animation-",
    "CODELORE|world-chunk-streamer.js|0012|frame yield inside every chunk: the outer pump owns the frame",
    "CODELORE|world-chunk-streamer.js|0013|budget and can usually finish several chunks per frame.",
    "CODELORE|world-chunk-streamer.js|0014|These states own no committed scene/physics resources. Dropping",
    "CODELORE|world-chunk-streamer.js|0015|them is both safe and important: otherwise a long walk leaves an",
    "CODELORE|world-chunk-streamer.js|0016|ever-growing history of stale queue records behind the player.",
    "CODELORE|world-chunk-streamer.js|0017|Farthest first gets memory back fastest if the player teleported.",
    "CODELORE|world-chunk-streamer.js|0018|The player may cross a chunk boundary while an earlier chunk",
    "CODELORE|world-chunk-streamer.js|0019|is cooperatively building. Refresh the queue before every",
    "CODELORE|world-chunk-streamer.js|0020|selection so a long pump follows the player instead of",
    "CODELORE|world-chunk-streamer.js|0021|finishing a stale ring around where the pump began.",
    "CODELORE|world-chunk-streamer.js|0022|Budget only between complete chunks. This preserves atomic",
    "CODELORE|world-chunk-streamer.js|0023|chunk commits while allowing a fast machine to crunch through",
    "CODELORE|world-chunk-streamer.js|0024|many ~millisecond chunks in the same rendered frame.",
    "CODELORE|world-chunk-streamer.js|0025|Adopt geometry that was authored by a specialized bootstrap generator.",
    "CODELORE|world-chunk-streamer.js|0026|This is how the rich hand-authored spawn district becomes logical chunk",
    "CODELORE|world-chunk-streamer.js|0027|(0,0) without rebuilding it through the generic infinite generator."
]);
