import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const hard = await import('./noise-data-hard.js');
const remote = await import('./noise-data-remote.js');
const poetry = await import('./noise-data-poetry.js');

function sampleEvenly(arr, target) {
  if (!Array.isArray(arr) || arr.length <= target) return Array.isArray(arr) ? arr : [];
  const out = [];
  const step = arr.length / target;
  for (let i = 0; i < target; i++) out.push(arr[Math.min(arr.length - 1, Math.floor(i * step))]);
  return out;
}

const sizes = {
  UNICODE_NOISE: 1536,
  MIME_NOISE: 768,
  SERVICE_NOISE: 1536,
  PROTOCOL_NOISE: 256,
  TIMEZONE_NOISE: 512,
  INDEX_STATUS_NOISE: 512,
  IANA_PORTS_NOISE: 1536,
  IANA_TLDS_NOISE: 768,
  RFC_INDEX_NOISE: 1024,
  OURAIRPORTS_AIRPORTS_NOISE: 2048,
  OURAIRPORTS_FREQUENCIES_NOISE: 1024,
  OURAIRPORTS_RUNWAYS_NOISE: 1024,
  OURAIRPORTS_NAVAIDS_NOISE: 1024,
  GEONAMES_CITIES500_NOISE: 3072,
  NOAA_GHCND_STATIONS_NOISE: 2048,
  USGS_EARTHQUAKES_MONTH_NOISE: 1536,
  POETRY_SHORT_NOISE: 1536,
  POETRY_MEDIUM_NOISE: 614,
  POETRY_PAIRS_NOISE: 667,
};

const values = {};
for (const name of ['UNICODE_NOISE','MIME_NOISE','SERVICE_NOISE','PROTOCOL_NOISE','TIMEZONE_NOISE','INDEX_STATUS_NOISE']) {
  values[name] = sampleEvenly(hard[name], sizes[name]);
}
for (const name of ['IANA_PORTS_NOISE','IANA_TLDS_NOISE','RFC_INDEX_NOISE','OURAIRPORTS_AIRPORTS_NOISE','OURAIRPORTS_FREQUENCIES_NOISE','OURAIRPORTS_RUNWAYS_NOISE','OURAIRPORTS_NAVAIDS_NOISE','GEONAMES_CITIES500_NOISE','NOAA_GHCND_STATIONS_NOISE','USGS_EARTHQUAKES_MONTH_NOISE']) {
  values[name] = sampleEvenly(remote[name], sizes[name]);
}
for (const name of ['POETRY_SHORT_NOISE','POETRY_MEDIUM_NOISE','POETRY_PAIRS_NOISE']) {
  values[name] = sampleEvenly(poetry[name], sizes[name]);
}

const concreteRows = Object.entries(values).filter(([k]) => !k.startsWith('POETRY_')).reduce((n,[,v]) => n + v.length, 0);
const remoteRows = Object.entries(values).filter(([k]) => ['IANA_PORTS_NOISE','IANA_TLDS_NOISE','RFC_INDEX_NOISE','OURAIRPORTS_AIRPORTS_NOISE','OURAIRPORTS_FREQUENCIES_NOISE','OURAIRPORTS_RUNWAYS_NOISE','OURAIRPORTS_NAVAIDS_NOISE','GEONAMES_CITIES500_NOISE','NOAA_GHCND_STATIONS_NOISE','USGS_EARTHQUAKES_MONTH_NOISE'].includes(k)).reduce((n,[,v]) => n + v.length, 0);

let src = `// Generated by build_bootstrap_noise_pack.mjs.\n// Critical-path text corpus: deterministic, representative samples of the full local datasets.\n// Full source corpora stay in-repo for archival/offline use but are deliberately NOT fetched at startup.\n\n`;
for (const [name, arr] of Object.entries(values)) {
  src += `export const ${name} = ${JSON.stringify(arr)};\n`;
}
src += `\nexport const NOISE_ACTIONS = ${JSON.stringify(hard.NOISE_ACTIONS)};\n`;
src += `export const MASSIVE_NOISE_META = ${JSON.stringify({...hard.MASSIVE_NOISE_META, concreteRows, bootstrap:true, sourceConcreteRows:hard.MASSIVE_NOISE_META.concreteRows})};\n`;
const remoteSources = {};
for (const [key, meta] of Object.entries(remote.REMOTE_NOISE_META.sources)) remoteSources[key] = {...meta, rows: Math.min(meta.rows ?? 0, sizes[({
  iana_ports:'IANA_PORTS_NOISE', iana_tlds:'IANA_TLDS_NOISE', rfc_index:'RFC_INDEX_NOISE', ourairports_airports:'OURAIRPORTS_AIRPORTS_NOISE', ourairports_frequencies:'OURAIRPORTS_FREQUENCIES_NOISE', ourairports_runways:'OURAIRPORTS_RUNWAYS_NOISE', ourairports_navaids:'OURAIRPORTS_NAVAIDS_NOISE', geonames_cities500:'GEONAMES_CITIES500_NOISE', noaa_ghcnd_stations:'NOAA_GHCND_STATIONS_NOISE', usgs_earthquakes_month:'USGS_EARTHQUAKES_MONTH_NOISE'
})[key]] ?? meta.rows ?? 0), sampled:true};
src += `export const REMOTE_NOISE_META = ${JSON.stringify({...remote.REMOTE_NOISE_META, rows:remoteRows, bootstrap:true, sourceRows:remote.REMOTE_NOISE_META.rows, sources:remoteSources})};\n`;
src += `export const POETRY_NOISE_META = ${JSON.stringify({...poetry.POETRY_NOISE_META, totalLines:values.POETRY_SHORT_NOISE.length + values.POETRY_MEDIUM_NOISE.length, pairs:values.POETRY_PAIRS_NOISE.length, bootstrap:true, sourceTotalLines:poetry.POETRY_NOISE_META.totalLines})};\n`;
src += `\nconst _CONCRETE_POOLS = [UNICODE_NOISE, MIME_NOISE, SERVICE_NOISE, PROTOCOL_NOISE, TIMEZONE_NOISE, INDEX_STATUS_NOISE, IANA_PORTS_NOISE, IANA_TLDS_NOISE, RFC_INDEX_NOISE, OURAIRPORTS_AIRPORTS_NOISE, OURAIRPORTS_FREQUENCIES_NOISE, OURAIRPORTS_RUNWAYS_NOISE, OURAIRPORTS_NAVAIDS_NOISE, GEONAMES_CITIES500_NOISE, NOAA_GHCND_STATIONS_NOISE, USGS_EARTHQUAKES_MONTH_NOISE];\n`;
src += `export function pickMassiveNoisePair(rng) { const pool = _CONCRETE_POOLS[Math.floor(rng() * _CONCRETE_POOLS.length)] || UNICODE_NOISE; const row = pool[Math.floor(rng() * pool.length)] || ['NO SIGNAL','NO SIGNAL']; return Array.isArray(row) ? [String(row[0] ?? 'NO SIGNAL'), String(row[1] ?? row[0] ?? 'NO SIGNAL')] : [String(row), String(row)]; }\n`;
src += `export function pickPoetryTag(rng) { const pool = rng() < 0.82 ? POETRY_SHORT_NOISE : POETRY_MEDIUM_NOISE; return String(pool[Math.floor(rng() * pool.length)] ?? 'NO SIGNAL'); }\n`;

fs.writeFileSync(path.join(here, 'noise-data-bootstrap.js'), src);
console.log(JSON.stringify({bytes:Buffer.byteLength(src), concreteRows, remoteRows, poetryLines: values.POETRY_SHORT_NOISE.length + values.POETRY_MEDIUM_NOISE.length, poetryPairs:values.POETRY_PAIRS_NOISE.length}, null, 2));
