const freezeDeep = (value) => {
    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
    Object.freeze(value);
    for (const item of Object.values(value)) freezeDeep(item);
    return value;
};

const DEFAULT_SCREEN = Object.freeze({
    activationDistanceM: 30,
    sleepDistanceM: 42,
    audioNearDistanceM: 3.5,
    audioFarDistanceM: 20,
    audioMaxVolume: 0.72,
    audioCurve: 1.45,
    retryDelayMs: 15000,
    defaultMuted: true,
});

const channels = [
    {
        sourceKey: 'live-news.al-jazeera-english',
        label: 'Al Jazeera English Live',
        provider: 'Al Jazeera',
        genres: ['news'],
        live: true,
        audio: true,
        radioEligible: true,
        selectable: true,
        weight: 0.6,
        readiness: 'existing-jweb-source',
        transportPolicy: { youtube: false, rawRestream: 'existing-jweb-source-only' },
        officialPageUrl: 'https://www.aljazeera.com/video/live',
        playback: { strategy: 'delegate-existing-resolver' },
        rights: {
            status: 'existing-jweb-policy',
            note: 'Keep the current JWEB Al Jazeera source as the only news channel. This pack does not create a second news provider.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['real-tv', 'linear', 'current-reality', 'only-news'],
    },
    {
        sourceKey: 'live-arts.classic-arts-showcase',
        label: 'Classic Arts Showcase',
        provider: 'Classic Arts Showcase',
        genres: ['arts', 'classical', 'performance'],
        live: true,
        audio: true,
        radioEligible: true,
        selectable: false,
        weight: 1.2,
        readiness: 'rights-good-web-transport-needs-confirmation',
        transportPolicy: { youtube: false, rawRestream: false },
        officialPageUrl: 'https://www.classicartsshowcase.org/',
        playback: { strategy: 'provider-transport-pending' },
        rights: {
            status: 'broadcast-friendly',
            evidenceUrl: 'https://www.classicartsshowcase.org/channel-list/information-for-broadcasters/',
            note: 'CAS says its 24-hour programming is free to broadcast, cable and PEG channels. Do not invent a web restream endpoint; add one only after the web transport is confirmed.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['real-tv', 'linear', 'ballet', 'opera', 'classic-film', 'painting', 'sculpture'],
    },
    {
        sourceKey: 'live-space.nasa-plus',
        label: 'NASA Live / NASA+',
        provider: 'NASA',
        genres: ['space', 'science'],
        live: true,
        audio: true,
        radioEligible: true,
        selectable: false,
        weight: 1.0,
        readiness: 'official-media-transport-pending',
        transportPolicy: { youtube: false, rawRestream: false },
        officialPageUrl: 'https://www.nasa.gov/live/',
        playback: { strategy: 'provider-transport-pending' },
        rights: {
            status: 'government-media-guidelines',
            evidenceUrl: 'https://www.nasa.gov/nasa-brand-center/images-and-media/',
            attribution: 'NASA',
            note: 'NASA content is generally not subject to U.S. copyright, subject to NASA media, branding, third-party-content and endorsement rules. Keep transport on official non-YouTube surfaces.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['real-tv', 'missions', 'launches', 'spaceflight'],
    },
    {
        sourceKey: 'live-space.nasa-station-views',
        label: 'Space Station Views with Mission Audio',
        provider: 'NASA',
        genres: ['space', 'ambient', 'science'],
        live: true,
        audio: 'varies',
        radioEligible: true,
        selectable: false,
        weight: 1.6,
        readiness: 'official-media-transport-pending',
        transportPolicy: { youtube: false, rawRestream: false },
        officialPageUrl: 'https://www.nasa.gov/multimedia/',
        playback: { strategy: 'provider-transport-pending', programHint: 'Space Station Views with Mission Audio' },
        rights: {
            status: 'government-media-guidelines',
            evidenceUrl: 'https://www.nasa.gov/nasa-brand-center/images-and-media/',
            attribution: 'NASA',
            note: 'Prefer the NASA-hosted live surface. Do not silently fall back to YouTube.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['real-tv', 'earth-from-space', 'iss', 'mission-audio'],
    },
    {
        sourceKey: 'live-public-affairs.dvids',
        label: 'DVIDS Live Roulette',
        provider: 'DVIDS',
        genres: ['public-affairs', 'military', 'ceremonies'],
        live: true,
        audio: true,
        radioEligible: true,
        selectable: true,
        weight: 1.25,
        readiness: 'live-bridge-ready',
        transportPolicy: { youtube: false, rawRestream: true },
        officialPageUrl: 'https://www.dvidshub.net/webcast/',
        playback: { strategy: 'dvids-live-bridge', metadataUrl: 'https://raw.githubusercontent.com/JustinBrownDev/justinbrowndev.github.io/jweb-media-runtime/dvids-live.json' },
        rights: {
            status: 'api-commercial-use',
            evidenceUrl: 'https://api.dvidshub.net/docs/tos',
            attribution: 'DVIDS / producing journalist when available',
            note: 'DVIDS API terms say media assets and information accessible via the API are free for commercial use. Follow DVIDS player/branding and attribution requirements.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['real-tv', 'live-events', 'graduations', 'briefings', 'federal'],
    },
    {
        sourceKey: 'live-science.nih-videocast',
        label: 'NIH VideoCast Live',
        provider: 'NIH VideoCast',
        genres: ['science', 'lectures', 'public-affairs'],
        live: true,
        audio: true,
        radioEligible: true,
        selectable: false,
        weight: 1.05,
        readiness: 'event-embed-discovery-pending',
        transportPolicy: { youtube: false, rawRestream: false },
        officialPageUrl: 'https://videocast.nih.gov/',
        playback: { strategy: 'unrestricted-event-embed-pending' },
        rights: {
            status: 'event-specific',
            note: 'Use only unrestricted NIH VideoCast events and preserve event-specific rights notices. Never assume every archived or live event has identical rights.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['real-tv', 'biomedical', 'seminar', 'conference', 'lecture'],
    },
    {
        sourceKey: 'live-nature.noaa-ocean-explorer',
        label: 'NOAA Ocean Exploration',
        provider: 'NOAA Ocean Exploration',
        genres: ['nature', 'ocean', 'science'],
        live: true,
        audio: 'during-dives',
        radioEligible: true,
        selectable: false,
        weight: 1.5,
        readiness: 'blocked-by-no-youtube-transport-policy',
        transportPolicy: { youtube: false, rawRestream: false },
        officialPageUrl: 'https://oceanexplorer.noaa.gov/livestreams/',
        playback: { strategy: 'provider-transport-pending' },
        rights: {
            status: 'public-domain-archive',
            evidenceUrl: 'https://oceanexplorer.noaa.gov/about/media-kit/',
            attribution: 'NOAA Ocean Exploration',
            note: 'NOAA Ocean Exploration archive video is public domain, but the current live page embeds YouTube. Keep this channel cataloged but non-selectable until a non-YouTube live transport is available.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['deep-sea', 'rov', 'abyss', 'animals', 'ambient'],
    },
    {
        sourceKey: 'live-nature.usgs-kilauea',
        label: 'USGS Kilauea',
        provider: 'U.S. Geological Survey',
        genres: ['nature', 'volcano', 'science', 'ambient'],
        live: true,
        audio: false,
        radioEligible: false,
        selectable: false,
        weight: 1.25,
        readiness: 'official-camera-transport-pending',
        transportPolicy: { youtube: false, rawRestream: false },
        officialPageUrl: 'https://www.usgs.gov/volcanoes/kilauea/webcams',
        playback: { strategy: 'official-camera-transport-pending' },
        rights: {
            status: 'us-government-media',
            attribution: 'USGS',
            note: 'Use the official USGS camera surface or a specifically documented reusable stream endpoint. Still-image webcams can be treated as low-rate television when appropriate.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['lava', 'crater', 'night', 'earth-science'],
    },
    {
        sourceKey: 'linear-cartoons.blender-open-movies',
        label: 'JWEB Cartoons - Blender Open Movies',
        provider: 'JWEB / Blender Open Movies',
        genres: ['cartoons', 'animation', 'movies'],
        live: false,
        linear: true,
        audio: true,
        radioEligible: true,
        selectable: true,
        weight: 1.8,
        readiness: 'resolver-ready',
        transportPolicy: { youtube: false, rawRestream: true },
        officialPageUrl: 'https://video.blender.org/c/blender_open_movies',
        playback: { strategy: 'blender-peertube-linear' },
        rights: {
            status: 'open-movie-licenses',
            note: 'Resolve only explicit allowlisted Blender Open Movie titles from Blender official PeerTube. Preserve per-video license and attribution data returned by PeerTube.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['jweb-linear', 'cartoon-channel', 'open-movies', 'same-program-by-wall-clock'],
    },
    {
        sourceKey: 'linear-movies.loc-public-domain',
        label: 'JWEB Movies - Library of Congress Public Domain',
        provider: 'JWEB / Library of Congress',
        genres: ['movies', 'old-film', 'educational', 'cartoons'],
        live: false,
        linear: true,
        audio: 'varies',
        radioEligible: true,
        selectable: false,
        weight: 1.5,
        readiness: 'catalog-ready-item-resolution-pending',
        transportPolicy: { youtube: false, rawRestream: true },
        officialPageUrl: 'https://www.loc.gov/free-to-use/public-domain-films-from-the-national-film-registry',
        playback: { strategy: 'loc-public-domain-linear-pending' },
        rights: {
            status: 'public-domain-curation',
            evidenceUrl: 'https://www.loc.gov/collections/selections-from-the-national-film-registry/about-this-collection/rights-and-access/',
            attribution: 'Library of Congress, Motion Picture, Broadcasting, and Recorded Sound Division',
            note: 'Use only the LOC free-to-use/public-domain selections and inspect item-level rights metadata before adding a direct media URL.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['jweb-linear', 'old-movies', 'industrial-film', 'public-domain', 'same-program-by-wall-clock'],
    },
    {
        sourceKey: 'live-public-access.curated',
        label: 'Public Access Roulette',
        provider: 'Curated PEG stations',
        genres: ['public-access', 'local-tv', 'weird'],
        live: true,
        audio: true,
        radioEligible: true,
        selectable: false,
        weight: 1.2,
        readiness: 'allowlist-empty',
        transportPolicy: { youtube: false, rawRestream: 'per-entry' },
        playback: { strategy: 'curated-stream-allowlist', allowlist: 'publicAccess' },
        rights: {
            status: 'per-station',
            note: 'Nothing enters this channel until the station explicitly supports third-party embedding/restreaming and the exact transport is recorded in the allowlist.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['real-tv', 'peg', 'community', 'local', 'roulette'],
    },
    {
        sourceKey: 'live-weird.owncast-curated',
        label: 'Owncast Weirdo Channel',
        provider: 'Opted-in Owncast operators',
        genres: ['weird', 'music', 'games', 'people'],
        live: true,
        audio: true,
        radioEligible: true,
        selectable: false,
        weight: 1.0,
        readiness: 'allowlist-empty',
        transportPolicy: { youtube: false, rawRestream: 'creator-opt-in' },
        officialPageUrl: 'https://owncast.online/docs/embed/',
        playback: { strategy: 'curated-stream-allowlist', allowlist: 'owncast' },
        rights: {
            status: 'creator-opt-in-required',
            note: 'Owncast supports embedding, but JWEB should whitelist only operators who explicitly opt into appearing inside the city.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['real-people', 'self-hosted', 'embed', 'roulette'],
    },
    {
        sourceKey: 'ambient-cams.curated',
        label: 'Ambient World Cams',
        provider: 'Explicit-embed camera providers',
        genres: ['ambient', 'nature', 'trains', 'cities', 'animals'],
        live: true,
        audio: 'varies',
        radioEligible: false,
        selectable: false,
        weight: 0.85,
        readiness: 'allowlist-empty',
        transportPolicy: { youtube: false, rawRestream: 'per-entry' },
        playback: { strategy: 'curated-stream-allowlist', allowlist: 'ambient' },
        rights: {
            status: 'per-camera',
            note: 'Home for the earlier South Pole, elk, desert waterhole, osprey, rail, volcano, river and city-camera ideas. Only add a concrete camera after its provider terms and non-YouTube transport are recorded.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['low-intensity', 'background-tv', 'camera-roulette'],
    },
    {
        sourceKey: 'experimental-filmon.genre-channels',
        label: 'FilmOn Genre Channels - HOLD',
        provider: 'FilmOn',
        genres: ['b-movie', 'horror', 'movies'],
        live: true,
        audio: true,
        radioEligible: true,
        selectable: false,
        weight: 0,
        readiness: 'rights-investigation',
        transportPolicy: { youtube: false, rawRestream: false },
        officialPageUrl: 'https://www.filmon.tv/',
        playback: { strategy: 'disabled' },
        rights: {
            status: 'investigate-do-not-use',
            note: 'Cataloged because the genre lineup is attractive, but deliberately disabled until affiliate/embed permission is unambiguous for JWEB use.',
        },
        screen: DEFAULT_SCREEN,
        tags: ['disabled', 'investigate', 'b-movie', 'horror'],
    },
];

export const MEDIA_CHANNELS = freezeDeep(channels);
export const MEDIA_CHANNEL_BY_KEY = freezeDeep(Object.fromEntries(MEDIA_CHANNELS.map((channel) => [channel.sourceKey, channel])));

export function getMediaChannel(sourceKey) {
    return MEDIA_CHANNEL_BY_KEY[sourceKey] ?? null;
}

export function listMediaChannels({ includeDisabled = true } = {}) {
    const rows = includeDisabled ? MEDIA_CHANNELS : MEDIA_CHANNELS.filter((channel) => channel.selectable);
    return Object.freeze(rows.slice());
}
